export const PRO_DATA = {'mindset:extraversion': 60,
'mindset:assertive': 58,  'mindset:cheerful': 71,  'mindset:energetic': 49, 
'mindset:friendly': 62,  'mindset:sociable': 67,  'mindset:openness': 44, 'mindset:ambitious': 76,
'mindset:disciplined': 60,  'mindset:dutiful': 41,  'mindset:organized': 58, 
'mindset:neuroticism': 43,
'mindset:anxiety prone': 51,  'mindset:impulsive': 59,
'mindset:stress prone': 61, 
'mindset:humble': 53,
'mindset:social': 65, 'mindset:inward focus': 39, 
'mindset:outward focus': 83,  'mindset:authentic': 61, 
'mindset:negations': 63,  'mindset:clout': 70,  'mindset:affiliation': 77, 
'mindset:achievement': 77,  'mindset:risk seeking': 60,  'mindset:risk aversion': 15,  'mindset:power': 51, 
'mindset:reward': 95}

export const CULTURE_DATA = {'mindset:extraversion': 62,
'mindset:assertive': 58,  'mindset:cheerful': 75,  'mindset:energetic': 51, 
'mindset:friendly': 64,  'mindset:sociable': 70,  'mindset:openness': 45, 'mindset:ambitious': 75, 
'mindset:disciplined': 61,  'mindset:dutiful': 44,  'mindset:organized': 53, 
'mindset:neuroticism': 43,
'mindset:anxiety prone': 49,  'mindset:impulsive': 60, 
'mindset:stress prone': 63,
'mindset:humble': 53,
'mindset:social': 73,  'mindset:inward focus': 37, 
'mindset:outward focus': 90,  'mindset:authentic': 63, 
'mindset:negations': 47,  'mindset:clout': 83,  'mindset:affiliation': 65, 
'mindset:achievement': 76,  'mindset:risk seeking': 59,  'mindset:risk aversion': 14,  'mindset:power': 52, 
'mindset:reward': 94}
